### ISSUE TITLE
Fix windows incompatibility with bpk babel include regex

### ISSUE THREAD

**Issue by matthewdavidson** [Skyscanner/full-stack-recruitment-test#4]
This regex is incompatible with windows: https://github.com/Skyscanner/full-stack-recruitment-test/blob/master/client/config/webpack.config.dev.js#L8

Potential solution is to just use a https://github.com/Skyscanner/backpack-react-scripts project (this is based off an old ejected CRA app).

**Comment by shaundon** [comment]
Closing as we have a PR to use Backpack React Scripts.
