### ISSUE TITLE
Small tweaks on the design

### ISSUE THREAD

**Issue by arnaugm** [Skyscanner/full-stack-recruitment-test#5]
A candidate noticed these small details:
- Font used in TopNav for Skyscanner's logo is different than the one provided with the sample design. The one present on the design seems to be more oblique.
- The Icon that's used for the Price alert action seems to be a little bit downscaled on the X axis.

**Comment by matthewdavidson** [comment]
@shaundon correct me if I am wrong but this issue should be resolved now?

**Comment by shaundon** [comment]
Yep! Nice one 😄
